In [23]:
import numpy as np
from numpy import array as array
from numpy import arange
from numpy.linalg import norm

In [15]:
a = np.zeros((3,3), np.float32)
print(a.dtype)
b = np.zeros((2,2), np.int64)
print(b.dtype)
print(f"item size of a: {a.dtype.itemsize}, b {b.dtype.itemsize}")

float32
int64
item size of a: 4, b 8


In [12]:
m = array([arange(3), arange(3)])
print(m)

[[0 1 2]
 [0 1 2]]


In [14]:
row_sum = m.sum(axis=0)
print(row_sum)
col_sum = m.sum(axis=-1)
print(col_sum)

[0 2 4]
[3 3]


In [17]:
a = arange(9)
b = a[3:7]
print(a)
print(b)
b[:] = 0
print(a)# 切片是共享数据的，改一个都会改
print(b)

[0 1 2 3 4 5 6 7 8]
[3 4 5 6]
[0 1 2 0 0 0 0 7 8]
[0 0 0 0]


In [20]:
a = arange(9)
c = a[:7:2].copy()# 如果要避免共享数据，就另外开辟一个
print(c)
c[:] = 0
print(a)
print(c)

[0 2 4 6]
[0 1 2 3 4 5 6 7 8]
[0 0 0 0]


In [24]:
v = arange(24).reshape((2,3,4))
print(v)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [25]:
z= norm(v, axis=0)
print(z)

[[12.         13.03840481 14.14213562 15.29705854]
 [16.4924225  17.72004515 18.97366596 20.24845673]
 [21.54065923 22.84731932 24.16609195 25.49509757]]


In [26]:
z=norm(v, axis=1)
print(z)

[[ 8.94427191 10.34408043 11.83215957 13.37908816]
 [28.28427125 29.9833287  31.68595904 33.39161571]]


In [27]:
z=norm(v, axis=-1)
print(z)

[[ 3.74165739 11.22497216 19.13112647]
 [27.09243437 35.07135583 43.05810028]]


In [40]:
a=arange(0,10).reshape((2,5)).T
print(a)
b= a[2].copy()
print(b)
z= b -a
print(z)
d = norm(z, axis=-1)
print(d)
print(f"min value: {np.min(d)}, min value idx: {np.argmin(d)}")

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
[2 7]
[[ 2  2]
 [ 1  1]
 [ 0  0]
 [-1 -1]
 [-2 -2]]
[2.82842712 1.41421356 0.         1.41421356 2.82842712]
min value: 0.0, min value idx: 2
